"""Add indexes for frequent filters

Revision ID: 8050864d5dbc
Revises: f1d6e5090946
Create Date: 2026-04-14 22:20:05.580559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8050864d5dbc'
down_revision = 'f1d6e5090946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CONVERSION_UNIDAD', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_CONVERSION_UNIDAD_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_CONVERSION_UNIDAD_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_CONVERSION_UNIDAD_unidad_destino_id'), ['unidad_destino_id'], unique=False)

    with op.batch_alter_table('INSUMO', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_INSUMO_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_INSUMO_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_INSUMO_unidad_base_id'), ['unidad_base_id'], unique=False)

    with op.batch_alter_table('MERMA', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MERMA_fecha_registro'), ['fecha_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_MERMA_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_MERMA_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_merma_is_active_fecha_registro', ['is_active', 'fecha_registro'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detalle_venta_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalle_venta_venta_id'), ['venta_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('production_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_task_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_task_fecha_limite'), ['fecha_limite'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_task_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_task_prioridad'), ['prioridad'], unique=False)
        batch_op.create_index('ix_production_task_prioridad_is_active_fecha_limite', ['prioridad', 'is_active', 'fecha_limite'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_task_receta_id'), ['receta_id'], unique=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_fecha_orden'), ['fecha_orden'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_purchase_is_active_supplier_id', ['is_active', 'supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('purchase_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_detail_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_detail_purchase_id'), ['purchase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_detail_unidad_medida_id'), ['unidad_medida_id'], unique=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('recipe_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_detail_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_detail_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_detail_unidad_medida_id'), ['unidad_medida_id'], unique=False)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_categoria_insumos'), ['categoria_insumos'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_user_rol_asignado_is_active', ['rol_asignado', 'is_active'], unique=False)

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_fecha_hora'), ['fecha_hora'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_fecha_hora'))
        batch_op.drop_index(batch_op.f('ix_venta_cliente_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_rol_asignado_is_active')
        batch_op.drop_index(batch_op.f('ix_user_is_active'))

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_is_active'))
        batch_op.drop_index(batch_op.f('ix_supplier_categoria_insumos'))

    with op.batch_alter_table('recipe_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_detail_unidad_medida_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_detail_is_active'))
        batch_op.drop_index(batch_op.f('ix_recipe_detail_insumo_id'))

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_product_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_is_active'))

    with op.batch_alter_table('purchase_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_detail_unidad_medida_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_detail_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_detail_insumo_id'))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_supplier_id'))
        batch_op.drop_index('ix_purchase_is_active_supplier_id')
        batch_op.drop_index(batch_op.f('ix_purchase_is_active'))
        batch_op.drop_index(batch_op.f('ix_purchase_fecha_orden'))

    with op.batch_alter_table('production_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_task_receta_id'))
        batch_op.drop_index('ix_production_task_prioridad_is_active_fecha_limite')
        batch_op.drop_index(batch_op.f('ix_production_task_prioridad'))
        batch_op.drop_index(batch_op.f('ix_production_task_is_active'))
        batch_op.drop_index(batch_op.f('ix_production_task_fecha_limite'))
        batch_op.drop_index(batch_op.f('ix_production_task_estado'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_categoria'))

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalle_venta_venta_id'))
        batch_op.drop_index(batch_op.f('ix_detalle_venta_producto_id'))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_is_active'))

    with op.batch_alter_table('MERMA', schema=None) as batch_op:
        batch_op.drop_index('ix_merma_is_active_fecha_registro')
        batch_op.drop_index(batch_op.f('ix_MERMA_is_active'))
        batch_op.drop_index(batch_op.f('ix_MERMA_insumo_id'))
        batch_op.drop_index(batch_op.f('ix_MERMA_fecha_registro'))

    with op.batch_alter_table('INSUMO', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_INSUMO_unidad_base_id'))
        batch_op.drop_index(batch_op.f('ix_INSUMO_is_active'))
        batch_op.drop_index(batch_op.f('ix_INSUMO_categoria'))

    with op.batch_alter_table('CONVERSION_UNIDAD', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_CONVERSION_UNIDAD_unidad_destino_id'))
        batch_op.drop_index(batch_op.f('ix_CONVERSION_UNIDAD_is_active'))
        batch_op.drop_index(batch_op.f('ix_CONVERSION_UNIDAD_insumo_id'))

    # ### end Alembic commands ###
