"""Add 'pedido minimo' fiel to Product model

Revision ID: f1d6e5090946
Revises: 411826fb2a23
Create Date: 2026-04-14 21:38:57.981575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d6e5090946'
down_revision = '411826fb2a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_minimo', sa.Integer(), nullable=False, server_default='1', default=1))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('pedido_minimo')

    # ### end Alembic commands ###
